// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:nadagram/db/models/content.dart';
import 'package:nadagram/db/models/user.dart';
import 'package:nadagram/db/models/user_setting.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NadagramContentAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserSettingAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NadagramContentAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserSettingAdapter());
  }
}
